{% set version = "0.22.0" %}

package:
  name: h3ronpy
  version: {{ version }}

source:
  url: https://github.com/nmandery/h3ronpy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d31d41e91191ff4652e6d9d61939eebfaec0b0dccd89c71ac52f2ca8d9a1e6c5

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install ./h3ronpy -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
    - cargo-bundle-licenses
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
  host:
    - python
    - maturin >=1.7.0,<2.0
    - pip
  run:
    - python
    - arro3-core >=0.4
    - numpy >=1.24
  run_constrained:
    - geopandas >=1
    - pyarrow >=15
    - polars >=1

test:
  imports:
    - h3ronpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nmandery/h3ronpy
  summary: Data science toolkit for the H3 geospatial grid.
  license: MIT
  license_family: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt
  license_url: https://github.com/nmandery/h3ronpy/blob/main/h3ronpy/LICENSE.txt
  doc_url: https://h3ronpy.readthedocs.io/en/latest
  dev_url: https://github.com/nmandery/h3ronpy

extra:
  recipe-maintainers:
    - kylebarron
    - keewis
